import type { Metadata, Viewport } from "next";
import { Fredoka, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { profile } from "@/lib/data";

const display = Fredoka({
  variable: "--font-display-var",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const body = Plus_Jakarta_Sans({
  variable: "--font-body-var",
  subsets: ["latin"],
  display: "swap",
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fbfbfa" },
    { media: "(prefers-color-scheme: dark)", color: "#07070b" },
  ],
};

export const metadata: Metadata = {
  metadataBase: new URL(profile.url),
  title: {
    default: `${profile.name} | Software Engineer & Community Builder`,
    template: `%s | ${profile.name}`,
  },
  description: profile.bio,
  keywords: [
    "Brian Bazurto",
    "Software Engineer",
    "Computer Science",
    "FIU",
    "Next.js Developer",
    "Portfolio",
    "Code Crunch",
    "ColorStack",
    "Google Developer Group",
    "Workday Intern",
  ],
  authors: [{ name: profile.name, url: profile.url }],
  creator: profile.name,
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    url: profile.url,
    siteName: `${profile.name} — Portfolio`,
    title: `${profile.name} | Software Engineer & Community Builder`,
    description: profile.bio,
    locale: "en_US",
    // og image is generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: `${profile.name} | Software Engineer & Community Builder`,
    description: profile.bio,
    creator: "@brianbazurto",
    // twitter image is generated by app/twitter-image.tsx
  },
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/icon-512.png", type: "image/png", sizes: "512x512" },
    ],
    apple: "/apple-icon.png",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large" },
  },
  category: "technology",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      data-scroll-behavior="smooth"
      className={`${display.variable} ${body.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
